### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Jason3S** [elazarcoh/vscode-extension-packagejson-generator#1]
@elazarcoh,

You clearly put some effort into pulling this out and making it work.

The WebPack plugin is a nice touch.

This package has two different purposes:
1. Tool to keep `package.json/contributes.configuration` in sync with a configuration interface.
2. Library to read settings from VS Code (the config util).

I suggest keeping them in separate directories.

I tried to leave some comments in the code, but I don't know if that is the best thing.

**Comment by elazarcoh** [comment]
thanks.
I'll look into it next week hopefully.

**Comment by elazarcoh** [comment]
@Jason3S 
I got through the comments and fixed the code.
I integrated the package in my extension https://github.com/elazarcoh/simply-view-image-for-python-debugging/tree/dev/use-auto-config
I'll do it for one more extension I have, write some tests, and then I think it can be published.

What do you think?

**Comment by elazarcoh** [comment]
published: https://www.npmjs.com/package/vscode-extensions-json-generator
